#!/bin/bash
set -euo pipefail
BINARY_STORE_DIR=${BINARY_STORE_DIR:-/app/config/bin}

RUN_PARAMS="${RUN_PARAMS:-} --config-dir config"
RUN_PARAMS="${RUN_PARAMS} --identity-dir identity"

if [ -n "${VERSION_SERVER_URL:-}" ]; then
  RUN_PARAMS="${RUN_PARAMS} --version.server-address=${VERSION_SERVER_URL}"
fi

if [ "${AUTO_UPDATE:-}" != "true" ]; then
  AUTO_UPDATE="false"
fi

: ${STORJ_CONSOLE_ADDRESS:=0.0.0.0:14002}
export STORJ_CONSOLE_ADDRESS
SNO_RUN_PARAMS="${RUN_PARAMS}"
if [ -n "${STORAGE:-}" ]; then
  SNO_RUN_PARAMS="${SNO_RUN_PARAMS} --storage.allocated-disk-space=${STORAGE}"
fi

if [ -n "${ADDRESS:-}" ]; then
  SNO_RUN_PARAMS="${SNO_RUN_PARAMS} --contact.external-address=${ADDRESS}"
fi

if [ -n "${EMAIL:-}" ]; then
  SNO_RUN_PARAMS="${SNO_RUN_PARAMS} --operator.email=${EMAIL}"
fi

if [ -n "${WALLET:-}" ]; then
  SNO_RUN_PARAMS="${SNO_RUN_PARAMS} --operator.wallet=${WALLET}"
fi

if [ -n "${LOG_LEVEL:-}" ]; then
  SNO_RUN_PARAMS="${SNO_RUN_PARAMS} --log.level=${LOG_LEVEL}"
fi

if [ "${SETUP:-}" = "true" ]; then
  echo "Running /app/bin/storagenode setup $SNO_RUN_PARAMS ${*}"
  exec /app/bin/storagenode setup ${SNO_RUN_PARAMS} ${*}
else
  export STORJ_SUPERVISOR_BINARY_STORE_DIR="${BINARY_STORE_DIR}"
  export STORJ_SUPERVISOR_VERSION_SERVER_ADDRESS="${VERSION_SERVER_URL}"
  export STORJ_SUPERVISOR_BINARY_LOCATION="/app/bin/storagenode"

  echo "Running /app/bin/supervisor exec /app/bin/storagenode run $SNO_RUN_PARAMS ${*}"
  exec /app/bin/supervisor exec /app/bin/storagenode run $SNO_RUN_PARAMS ${*}
fi
